WITH SUFFOLK AS (SELECT DOSAGE_UNIT, TRANSACTION_DATE FROM CSE532.DEA_NY WHERE BUYER_COUNTY = 'SUFFOLK'), 
DATE AS (SELECT DOSAGE_UNIT AS TOTAL_DOSAGE,YEAR(TRANSACTION_DATE) || CASE WHEN (CAST(MONTH(TRANSACTION_DATE) AS INT) < 10) THEN '0'  || CAST(MONTH(TRANSACTION_DATE) AS INT) ELSE CAST (MONTH(TRANSACTION_DATE) AS CHAR(2)) END AS TRANS_DATE FROM SUFFOLK),
TEMP AS (SELECT CAST(SUM(TOTAL_DOSAGE) AS INT) AS NORMAL, TRANS_DATE FROM DATE GROUP BY TRANS_DATE)
SELECT NORMAL AS NORMAL, AVG(NORMAL) OVER ( ORDER BY TRANS_DATE ROWS BETWEEN 1 PRECEDING AND 1 FOLLOWING) AS SMOOTH, TRANS_DATE AS DATE(YYYY/MM) FROM TEMP;
